# Generated by Django 2.1.7 on 2019-03-24 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import web.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, validators=[web.models.empty_validate_event])),
                ('summery', models.TextField(blank=True)),
                ('recive_date', models.DateTimeField()),
                ('recive_number', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('add_by_usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
