# Generated by Django 2.1.7 on 2019-03-30 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190330_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recive',
            name='del_by_usr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='del_by_usr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='send',
            name='del_by_usr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='del_by_usr_send', to=settings.AUTH_USER_MODEL),
        ),
    ]
